name: upbit
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - pip:
    - PyJWT==2.8.0
    - requests==2.31.0
    - torch==2.1.0
    - stable-baselines3==2.2.1
    - gymnasium==0.29.1
    - ta==0.11.0
    - python-dotenv==1.0.0
    - pyyaml==6.0.1
